apiVersion: agentregistry.dev/v1alpha1
kind: DiscoveryConfig
metadata:
  name: abox
  namespace: agentregistry
spec:
  environments:
  - name: abox
    cluster:
      name: local
    namespaces:
    - kagent
    - mcp
    discoveryEnabled: true
