apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway.yaml
  - kagent.yaml
  - mcp.yaml
  - mcp-agentgateway.yaml
  - remote-agw-mcp.yaml
  - aire-agent.yaml
  - agentregistry.yaml
  - mcp-governance.yaml
  - qdrant.yaml
