apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab3-agent
  namespace: kagent
  labels:
    app: kagent
    kagent: lab3-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kagent
      kagent: lab3-agent
  template:
    metadata:
      labels:
        app: kagent
        kagent: lab3-agent
    spec:
      containers:
        - name: kagent
          image: cr.kagent.dev/kagent-dev/kagent/app:0.7.23
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 1
            failureThreshold: 3