apiVersion: v1
kind: Namespace
metadata:
  name: mcp
---
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: github-mcp-server
  namespace: mcp
  labels:
    kagent.dev/discovery: disabled
spec:
  deployment:
    args:
    - 'stdio'
    cmd: "/server/github-mcp-server"
    image: ghcr.io/github/github-mcp-server
    port: 3000
    secretRefs:
    - name: github-mcp-secret
  transportType: stdio
